process.env.NODE_ENV = 'test'
process.env.LOG_LEVEL = 'silent'
process.env.RECAPTCHA_ENABLED = '1'
process.env.RECAPTCHA_SCORE_THRESHOLD = '0.5'
process.env.EMAIL_SOURCE = 'john@email.com'
process.env.EMAIL_DEST = 'doe@email.com'
process.env.EMAIL_SUBJECT = 'Solicitação de orçamento'
