AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: dom-server

Globals:
  Function:
    Timeout: 30

Resources:
  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          NODE_ENV: production
          RECAPTCHA_SECRET: 6LeAZLEcAAAAAJwGNet_2qzgyGvJtG1QVx_udONl
          RECAPTCHA_SCORE_THRESHOLD: 0.5
          EMAIL_SOURCE: gmtfonseca@gmail.com
          EMAIL_DEST: gustavofonseca94@gmail.com
          EMAIL_SUBJECT: Solicitação de orçamento
      Policies:
        - Statement:
            - Sid: SESSendEmail
              Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'

            - Sid: SSMGetRecaptchaSecret
              Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: 'arn:aws:ssm:sa-east-1:491667351100:parameter/dom-server/recaptcha/secret'

            - Sid: KMSDecryptRecaptchaSecret
              Effect: Allow
              Action:
                - kms:Decrypt
              Resource: 'arn:aws:kms:sa-east-1:491667351100:key/e3505977-a7b6-4d1c-8f89-ac7055ebe467'
      Events:
        SendEmail:
          Type: HttpApi
          Properties:
            Path: /cart
            Method: post

Outputs:
  SendEmailApi:
    Description: 'API Gateway endpoint URL for SendEmailFunction'
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/cart/'
  SendEmailFunction:
    Description: SendEmailFunction ARN"
    Value: !GetAtt SendEmailFunction.Arn
  SendEmailFunctionIamRole:
    Description: 'Implicit IAM Role created for SendEmailFunctionIamRole'
    Value: !GetAtt SendEmailFunctionRole.Arn
